export const tasks = [
  {
    id: 500,
    text: "Mechanical Installation (Passenger Elevator)",
    type: "summary",
    start: null,
    end: null,
    duration: 45,
    parent: 0,
    open: true,
  },
  {
    id: 501,
    text: "Unloading of elevator equipments",
    type: "task",
    start: null,
    end: null,
    duration: 1,
    parent: 500,
  },
  {
    id: 502,
    text: "Scaffolding Installation",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
  },
  {
    id: 503,
    text: "Hauling Works",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
  },
  {
    id: 504,
    text: "Template Setting",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
  },
  {
    id: 505,
    text: "Marking and Boring of Holes",
    type: "task",
    start: null,
    end: null,
    duration: 1,
    parent: 500,
  },
  {
    id: 506,
    text: "Rail Bracket Installation",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
  },
  {
    id: 507,
    text: "Guide Rail Setting",
    type: "summary",
    start: null,
    end: null,
    duration: 5,
    parent: 500,
    open: false,
  },
  {
    id: 508,
    text: "Main/Car",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 507,
  },
  {
    id: 509,
    text: "Counterweight (CWT)",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 507,
  },
  {
    id: 510,
    text: "Gauging",
    type: "task",
    start: null,
    end: null,
    duration: 1,
    parent: 507,
  },
  {
    id: 511,
    text: "Landing Door Assembly",
    type: "summary",
    start: null,
    end: null,
    duration: 6,
    parent: 500,
    open: false,
  },
  {
    id: 512,
    text: "Sills and Supports",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 511,
  },
  {
    id: 513,
    text: "Jamb and Supports",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 511,
  },
  {
    id: 514,
    text: "Frame and Doors",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 511,
  },
  {
    id: 515,
    text: "M/R Equipment Setting",
    type: "summary",
    start: null,
    end: null,
    duration: 6,
    parent: 500,
    open: false,
  },
  {
    id: 516,
    text: "Traction Machine",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 515,
  },
  {
    id: 517,
    text: "Support Beams",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 515,
  },
  {
    id: 518,
    text: "Governor",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 515,
  },
  {
    id: 519,
    text: "Installation of Control Panel",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
  },
  {
    id: 520,
    text: "Car Assembly",
    type: "summary",
    start: null,
    end: null,
    duration: 3,
    parent: 500,
    open: false,
  },
  {
    id: 521,
    text: "All Accessories",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 520,
  },
  {
    id: 522,
    text: "Car Piping/Wiring",
    type: "task",
    start: null,
    end: null,
    duration: 1,
    parent: 520,
  },
  {
    id: 523,
    text: "Travelling Cable Layout",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
  },
  {
    id: 524,
    text: "Counterweight Assembly",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
  },
  {
    id: 525,
    text: "Laying out of Ropes",
    type: "summary",
    start: null,
    end: null,
    duration: 5,
    parent: 500,
    open: false,
  },
  {
    id: 526,
    text: "Hoisting",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 525,
  },
  {
    id: 527,
    text: "Governor",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 525,
  },
  {
    id: 528,
    text: "Compensating",
    type: "task",
    start: null,
    end: null,
    duration: 1,
    parent: 525,
  },
  {
    id: 529,
    text: "Wiring",
    type: "summary",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
    open: false,
  },
  {
    id: 530,
    text: "Machine Room",
    type: "task",
    start: null,
    end: null,
    duration: 1,
    parent: 529,
  },
  {
    id: 531,
    text: "Hoistway",
    type: "task",
    start: null,
    end: null,
    duration: 1,
    parent: 529,
  },
  {
    id: 532,
    text: "Installation of Pit Ladder / Hoistway Lighting",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 500,
  },
  {
    id: 600,
    text: "Testing and Commissioning (Passenger Elevator)",
    type: "summary",
    start: null,
    end: null,
    duration: 15,
    parent: 0,
    open: true,
  },
  {
    id: 601,
    text: "Initial testing",
    type: "task",
    start: null,
    end: null,
    duration: 3,
    parent: 600,
  },
  {
    id: 602,
    text: "Slow speed",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 600,
  },
  {
    id: 603,
    text: "High speed and Mechanical Adjustment",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 600,
  },
  {
    id: 604,
    text: "Load Test",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 600,
  },
  {
    id: 605,
    text: "Final Adjust",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 600,
  },
  {
    id: 606,
    text: "Features Test / Correction of Defects",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 600,
  },
  {
    id: 607,
    text: "Final Cleaning / Hand over",
    type: "task",
    start: null,
    end: null,
    duration: 2,
    parent: 600,
  },
];
